(function () {
  // Auto-generated by scripts/generate-movement-manifest.js. Do not edit by hand.
  const movementDataFiles = [
    './movements/abolition-of-slavery-data.js',
    './movements/american-revolution-data.js',
    './movements/catholic-church-data.js',
    './movements/handwashing-hygiene-data.js',
    './movements/me-too-data.js',
    './movements/upside-data.js',
    './movements/womens-suffrage-data.js'
  ];

  if (typeof window !== 'undefined') {
    window.movementDataFiles = movementDataFiles;
    movementDataFiles.forEach(src => {
      // document.write keeps loading synchronous relative to this script tag,
      // ensuring movement datasets are available before movement-data.js runs.
      document.write('<script src="' + src + '"></' + 'script>');
    });
  } else if (typeof module !== 'undefined') {
    module.exports = movementDataFiles;
  }
})();
