(function () {
  // Auto-generated by scripts/generate-movement-manifest.js. Do not edit by hand.
  const movementDataFiles = [
    "./movements/abolition-of-slavery-data.js",
    "./movements/american-revolution-data.js",
    "./movements/catholic-church-data.js",
    "./movements/handwashing-hygiene-data.js",
    "./movements/me-too-data.js",
    "./movements/race-for-the-cure/claims/awareness-claim-data.js",
    "./movements/race-for-the-cure/claims/fundraising-claim-data.js",
    "./movements/race-for-the-cure/race-base-data.js",
    "./movements/race-for-the-cure/rules/safety-rule-data.js",
    "./movements/race-for-the-cure/rules/volunteer-rule-data.js",
    "./movements/reknit-december-15/claims/corporate-productization-claim-data.js",
    "./movements/reknit-december-15/claims/in-person-weaving-claim-data.js",
    "./movements/reknit-december-15/claims/tech-isolating-claim-data.js",
    "./movements/reknit-december-15/entities/reknit-entities-data.js",
    "./movements/reknit-december-15/reknit-base-data.js",
    "./movements/reknit-december-15/relations/reknit-relations-data.js",
    "./movements/reknit-december-15/texts/corporate-productization-text-data.js",
    "./movements/reknit-december-15/texts/in-person-meetings-text-data.js",
    "./movements/reknit-december-15/texts/reknit-manifesto-data.js",
    "./movements/reknit-december-15/texts/tech-isolating-text-data.js",
    "./movements/upside-data.js",
    "./movements/womens-suffrage-data.js"
  ];

  function escapeHtml(value) {
    return String(value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }

  function showFatalBanner(title, details) {
    try {
      const el = document.createElement('div');
      el.id = 'movement-data-fatal-banner';
      el.setAttribute(
        'style',
        [
          'position:fixed',
          'top:0',
          'left:0',
          'right:0',
          'max-height:60vh',
          'overflow:auto',
          'background:#b00020',
          'color:#fff',
          'padding:14px 16px',
          'z-index:2147483647',
          'font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif',
          'box-shadow:0 2px 12px rgba(0,0,0,0.35)'
        ].join(';')
      );

      el.innerHTML =
        '<div style="font-weight:700;font-size:16px;margin-bottom:8px;">' +
        escapeHtml(title) +
        '</div>' +
        '<pre style="margin:0;white-space:pre-wrap;font-size:12px;line-height:1.35;">' +
        escapeHtml(details) +
        '</pre>';

      (document.body || document.documentElement).appendChild(el);
    } catch (e) {
      console.error(title);
      console.error(details);
    }
  }

  if (typeof window !== 'undefined') {
    window.movementDataFiles = movementDataFiles;

    const state = {
      expected: movementDataFiles.slice(),
      pushedBySrc: {},
      errors: []
    };

    window.__movementDataLoadState = state;
    window.__showMovementDataFatalBanner = showFatalBanner;

    window.__movementDataReportError = function (err) {
      state.errors.push(err);
      console.error('[movement-data]', err);
    };

    // Catch parse/runtime errors coming from movement dataset scripts.
    window.addEventListener(
      'error',
      function (event) {
        try {
          const filename = event && event.filename ? String(event.filename) : '';
          const isDataset =
            filename.includes('/movements/') && filename.endsWith('-data.js');

          if (isDataset) {
            window.__movementDataReportError({
              type: 'runtime',
              src: filename,
              message: event.message,
              lineno: event.lineno,
              colno: event.colno
            });
          }
        } catch (e) {}
      },
      true
    );

    // Ensure datasets array exists and instrument .push so we can detect per-file registration.
    window.movementDatasets = Array.isArray(window.movementDatasets)
      ? window.movementDatasets
      : [];

    (function instrumentDatasetPush() {
      const datasets = window.movementDatasets;
      const originalPush = datasets.push;

      datasets.push = function () {
        const src = window.__movementDataCurrentSrc || 'unknown';
        state.pushedBySrc[src] = (state.pushedBySrc[src] || 0) + arguments.length;
        return originalPush.apply(datasets, arguments);
      };
    })();

    window.__movementDataScriptError = function (src) {
      window.__movementDataReportError({ type: 'load', src: src });
    };

    window.__movementDataFinalizeOrThrow = function () {
      const expected = state.expected;
      const pushed = state.pushedBySrc;
      const errors = state.errors;

      const missing = expected.filter(src => !pushed[src]);
      const multiple = expected.filter(src => (pushed[src] || 0) > 1);
      const unknown = Object.keys(pushed).filter(src => expected.indexOf(src) === -1);

      if (errors.length || missing.length || multiple.length || unknown.length) {
        const lines = [];
        lines.push('Movement datasets failed to load.');
        lines.push('');

        if (errors.length) {
          lines.push('Errors:');
          errors.forEach((e, i) => {
            lines.push(
              '  ' +
                (i + 1) +
                '. [' +
                e.type +
                '] ' +
                (e.src || 'unknown') +
                (e.message ? ': ' + e.message : '')
            );
          });
          lines.push('');
        }

        if (missing.length) {
          lines.push('No dataset registered from these files:');
          missing.forEach(src => lines.push('  - ' + src));
          lines.push('');
        }

        if (multiple.length) {
          lines.push('Multiple datasets registered from these files (expected exactly 1):');
          multiple.forEach(src => lines.push('  - ' + src + ' (count=' + pushed[src] + ')'));
          lines.push('');
        }

        if (unknown.length) {
          lines.push('Datasets registered while "current src" was unknown/unexpected:');
          unknown.forEach(src => lines.push('  - ' + src + ' (count=' + pushed[src] + ')'));
          lines.push('');
        }

        const details = lines.join('\n');
        showFatalBanner('Reknit failed to boot (movement data)', details);
        throw new Error(details);
      }
    };

    // Load datasets synchronously (relative to this manifest script tag).
    movementDataFiles.forEach(src => {
      document.write('<script>window.__movementDataCurrentSrc=' + JSON.stringify(src) + ';</' + 'script>');
      document.write(
        '<script src="' +
          src +
          '" data-movement-dataset="true" onerror="window.__movementDataScriptError(this.getAttribute(\'src\'))"></' +
          'script>'
      );
    });

    // Run final verification AFTER all scripts above.
    document.write('<script>window.__movementDataFinalizeOrThrow();</' + 'script>');
  } else if (typeof module !== 'undefined') {
    module.exports = movementDataFiles;
  }
})();
